### ISSUE TITLE
Add documentation on official Arduino Docs Website

### ISSUE THREAD

**Issue by sebromero** [khoih-prog/Portenta_H7_AsyncHTTPRequest#1]
**Is your feature request related to a problem? Please describe.**
You created a couple of very useful and advanced libraries that deserve some more visibility.

**Describe the solution you'd like**
Collaborate with Arduino on creating tutorials around your libraries.

**Additional context**
Couldn't find your contact details anywhere, so I created this issue 😄. Let me know if you're interested in sharing the great stuff that you created with a bigger audience.

**Comment by khoih-prog** [comment]
Hi @sebromero 

Thanks for the offer. I just fix the typo in `library.json` to correct my email address.

Even I'm very interested in this, I still don't know what I can do and help contribute to the tutorials. As you know, we, as programmer, are the **worst people** to make documents / tutorials.

I propose **Arduino** will assign the correct people to make all the interested tutorials, then I can scan through and point out if there is anything wrong and propose the fix in the process. The libraries are anyway all in public domain, with all the info there.

Best Regards,

**Comment by sebromero** [comment]
Thank you for your reply, I'll send you a PN 👍
